#include <stdio.h>
#include "builtins.h"

void builtins_init(FILE* outputfp) {
	const char* bootstrap =
		"\n## →→ These are built-in functions ←← ##\n"
		"print:\n"
		"	pushl %%ebp\n"
		"	movl %%esp, %%ebp\n"
		"	pushl 8(%%ebp)\n"
		"	call strlen\n"
		"	movl %%eax, %%edx\n"
		"	movl $4, %%eax\n"
		"	movl $1, %%ebx\n"
		"	movl 8(%%ebp), %%ecx\n"
		"	int $0x80\n"
		"	leave\n"
		"	ret\n"
		"printi:\n"
		"	pushl %%ebp\n"
		"	movl %%esp, %%ebp\n"
		"	movl 8(%%ebp), %%eax\n"
		"	call printi_loop\n"
		"printi_loop:\n"
		"	movl $0, %%edx\n"
		"	movl $10, %%ebx\n"
		"	divl %%ebx\n"
		"	addl $48, %%edx\n"
		"	pushl %%edx\n"
		"	incl %%esi\n"
		"	cmpl $0, %%eax\n"
		"	jz   printi_next\n"
		"	jmp printi_loop\n"
		"printi_next:\n"
		"	cmpl $0, %%esi\n"
		"	jz   printi_exit\n"
		"	decl %%esi\n"
		"	movl $4, %%eax\n"
		"	movl %%esp, %%ecx\n"
		"	movl $1, %%ebx\n"
		"	movl $1, %%edx\n"
		"	int  $0x80\n"
		"	addl $4, %%esp\n"
		"	jmp  printi_next\n"
		"printi_exit:\n"
		"	movl $4, %%eax\n"
		"	movl $1, %%ebx\n"
		"	pushl $0x0a\n"
		"	movl $1, %%edx\n"
		"	int $0x80\n"
		"	leave\n"
		"	ret\n"
		"strlen:\n"
		"	movl $0, %%edi\n"
		"	movl 4(%%esp), %%ebx\n"
		"strlen_loop:\n"
		"	movb (%%ebx), %%al\n"
		"	cmpb $0, %%al\n"
		"	je strlen_exit\n"
		"	incl %%edi\n"
		"	incl %%ebx\n"
		"	jmp strlen_loop\n"
		"strlen_exit:\n"
		"	movl %%edi, %%eax\n"
		"	ret\n";
	fprintf(outputfp, bootstrap);
}
